In [1]:
import os
import importlib
import train_utils
import sanitize

importlib.reload(train_utils)  # 重新加载模块
importlib.reload(sanitize)  # 重新加载模块

os.chdir("c:\\Users\\HANJ29\\Applications\\deepstock\\")

from sanitize import merge_csv_files, map_labels, check_nan_values, extract_rows_from_n, drop_nan_values

freq = "D"

# 文件路径
stock_filestore_DEV = "C:/Users/HANJ29/Applications/btweb/stock_filestore/DEV/"
folder_ds_entry = "dataset_entry/"
folder_ds_tech_pattern = "dataset_tech_pattern/"
# folder_ds_tech_funda = "dataset_tech_funda/"
dataset_training = f"{stock_filestore_DEV}dataset_training/"
dataset_training_stat = f"{stock_filestore_DEV}dataset_training/stat/"

dataset_entry_path = f"{stock_filestore_DEV}{folder_ds_entry}{freq}/"
# dataset_tech_pattern_path = f"{stock_filestore_DEV}{folder_ds_tech_pattern}{FREQ}/"

In [2]:
input_features = [
    "ts_code",
    "trade_date",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "pct_change",
    "vol",
    "amount",
    "atr",
    "boll_upper",
    "boll_mid",
    "boll_lower",
    "pct_vol_chg",
    "pct_amount_chg",
    "pct_o2c",
    "lower_shadow",
    "upper_shadow",
    "dif",
    "dea",
    "bar",
    "rsi_6",
    "rsi_12",
    "rsi_24",
    "k",
    "d",
    "j",
    "cci",
    "mab_6",
    "mab_10",
    "mab_25",
    "mab_60",
    "mab_120",
    "mab_200",
    "is_lower_shadow_shape",
    "is_upper_shadow_shape",
    "is_doji_shape",
    "is_big_bullish",
    "is_bullish_divergent",
    "is_big_bearish",
    "is_support_ma_6",
    "is_support_ma_10",
    "is_support_ma_25",
    "is_support_ma_60",
    "is_support_ma_120",
    "is_support_ma_200",
    "ma_6_trend",
    "ma_10_trend",
    "ma_25_trend",
    "ma_60_trend",
    "ma_120_trend",
    "ma_200_trend",
    "is_ma_entangled_6_10",
    "is_ma_entangled_25_200",
    "is_ma_entangled_6_10_25",
    "is_ma_entangled_6_10_200",
    "is_ma_entangled_6_10_25_60_120_200",
    "vol_status_ma",
    "vol_status_ma10",
    "kdj_status",
    "rsi_status",
    "macd_status",
    "is_t_shape",
    "top_or_bottom",
    "top_or_bottom_stat",
    "top_bottom_volatility_stat",
    "top_or_bottom_stat_optimized",
    "top_or_bottom_optimized",
    "top_bottom_volatility_optimized",
]

In [3]:
tech_df = merge_csv_files(dataset_entry_path)

In [4]:
tech_df = tech_df[input_features]

In [5]:
tech_df.head(50)

,ts_code,trade_date,open,high,low,close,pre_close,pct_change,vol,amount,...,kdj_status,rsi_status,macd_status,is_t_shape,top_or_bottom,top_or_bottom_stat,top_bottom_volatility_stat,top_or_bottom_stat_optimized,top_or_bottom_optimized,top_bottom_volatility_optimized
0,000001.SZ,1991-04-04,0.36999,0.36999,0.36999,0.36999,0.37181,-0.49,3.0,15.0,...,0,0,0,0,N,N,N,N,N,N
1,000001.SZ,1991-04-05,0.36817,0.36817,0.36817,0.36817,0.36999,-0.49,2.0,10.0,...,0,2,0,0,N,N,N,N,N,N
2,000001.SZ,1991-04-08,0.36453,0.36453,0.36453,0.36453,0.36817,-0.99,2.0,10.0,...,0,2,0,0,N,N,N,N,N,N
3,000001.SZ,1991-04-09,0.36270,0.36270,0.36270,0.36270,0.36453,-0.50,4.0,19.0,...,0,2,0,0,N,N,N,N,N,N
4,000001.SZ,1991-04-10,0.36088,0.36088,0.36088,0.36088,0.36270,-0.50,15.0,71.0,...,0,2,0,0,N,N,N,N,N,N
5,000001.SZ,1991-04-12,0.35724,0.35724,0.35724,0.35724,0.36088,-1.01,8.0,38.0,...,0,2,0,0,N,N,N,N,N,N
6,000001.SZ,1991-04-16,0.35193,0.35193,0.35193,0.35193,0.35724,-1.49,2.0,9.0,...,0,2,0,0,N,N,N,N,N,N
7,000001.SZ,1991-04-17,0.35018,0.35018,0.35018,0.35018,0.35193,-0.50,1.0,5.0,...,0,2,0,0,N,N,N,N,N,N
8,000001.SZ,1991-04-18,0.34844,0.34844,0.34844,0.34844,0.35018,-0.50,4.0,18.0,...,2,2,0,0,N,N,N,N,N,N
9,000001.SZ,1991-04-19,0.34669,0.34669,0.34669,0.34669,0.34844,-0.50,2.0,9.0,...,2,2,0,0,N,N,N,N,N,N
10,000001.SZ,1991-04-23,0.34146,0.34146,0.34146,0.34146,0.34495,-1.01,28.0,126.0,...,2,2,0,0,N,N,N,N,N,N
11,000001.SZ,1991-04-24,0.33979,0.33979,0.33979,0.33979,0.34146,-0.49,16.0,72.0,...,2,2,0,0,N,N,N,N,N,N
12,000001.SZ,1991-04-25,0.33812,0.33812,0.33812,0.33812,0.33979,-0.49,15.0,67.0,...,2,2,0,0,N,N,N,N,N,N
13,000001.SZ,1991-04-26,0.33645,0.33645,0.33645,0.33645,0.33812,-0.49,8.0,35.0,...,2,2,0,0,N,N,N,N,N,N
14,000001.SZ,1991-04-29,0.33311,0.33311,0.33311,0.33311,0.33645,-0.99,4.0,17.0,...,2,2,0,0,N,N,N,N,N,N
15,000001.SZ,1991-04-30,0.33144,0.33144,0.33144,0.33144,0.33311,-0.50,2.0,9.0,...,2,2,0,0,B,B,B,B,B,B
16,000001.SZ,1991-05-02,0.46465,0.46465,0.46465,0.46465,0.33133,40.24,2.0,9.0,...,0,1,0,0,T,T,T,T,T,T
17,000001.SZ,1991-05-03,0.46230,0.46230,0.46230,0.46230,0.46465,-0.51,3.0,13.0,...,0,1,0,0,N,N,N,N,N,N
18,000001.SZ,1991-05-07,0.45535,0.45535,0.45535,0.45535,0.45995,-1.00,2.0,8.0,...,0,1,0,0,N,N,N,N,N,N
19,000001.SZ,1991-05-08,0.45310,0.45310,0.45310,0.45310,0.45535,-0.49,109.0,462.0,...,0,1,0,0,N,N,N,N,N,N
20,000001.SZ,1991-05-09,0.45086,0.45086,0.45086,0.45086,0.45310,-0.50,15.0,63.0,...,1,1,0,0,N,N,N,N,N,N
21,000001.SZ,1991-05-10,0.44861,0.44861,0.44861,0.44861,0.45086,-0.50,20.0,84.0,...,1,0,0,0,N,N,N,N,N,N
22,000001.SZ,1991-05-13,0.44412,0.44412,0.44412,0.44412,0.44861,-1.00,19.0,79.0,...,1,0,0,0,N,N,N,N,N,N
23,000001.SZ,1991-05-14,0.44188,0.44188,0.44188,0.44188,0.44412,-0.51,55.0,227.0,...,1,0,0,0,N,N,N,N,N,N
24,000001.SZ,1991-05-15,0.43963,0.43963,0.43963,0.43963,0.44188,-0.51,387.0,1591.0,...,0,0,0,0,N,N,N,N,N,N
25,000001.SZ,1991-05-16,0.43739,0.43739,0.43739,0.43739,0.43963,-0.51,493.0,2017.0,...,0,0,0,0,N,N,N,N,N,N
26,000001.SZ,1991-05-17,0.43525,0.43525,0.43525,0.43525,0.43739,-0.49,419.0,1706.0,...,0,0,0,0,N,N,N,N,N,N
27,000001.SZ,1991-05-20,0.43097,0.43097,0.43097,0.43097,0.43525,-0.98,51.0,205.0,...,2,0,0,0,N,N,N,N,N,N
28,000001.SZ,1991-05-21,0.42883,0.42883,0.42883,0.42883,0.43097,-0.50,63.0,253.0,...,2,0,0,0,N,N,N,N,N,N
29,000001.SZ,1991-05-22,0.42669,0.42669,0.42669,0.42669,0.42883,-0.50,43.0,171.0,...,2,0,0,0,N,N,N,N,N,N
30,000001.SZ,1991-05-23,0.42456,0.42456,0.42456,0.42456,0.42669,-0.50,17.0,67.0,...,2,0,0,0,N,N,N,N,N,N
31,000001.SZ,1991-05-24,0.42242,0.42242,0.42242,0.42242,0.42456,-0.50,3.0,12.0,...,2,0,0,0,N,N,N,N,N,N
32,000001.SZ,1991-05-27,0.41814,0.41814,0.41814,0.41814,0.42242,-1.01,5.0,19.0,...,2,0,0,0,N,N,N,N,N,N
33,000001.SZ,1991-05-28,0.41600,0.41600,0.41600,0.41600,0.41814,-0.51,3.0,12.0,...,2,0,0,0,N,N,N,N,N,N
34,000001.SZ,1991-05-29,0.41397,0.41397,0.41397,0.41397,0.41600,-0.49,36.0,139.0,...,2,0,0,0,N,N,N,N,N,N
35,000001.SZ,1991-05-30,0.41194,0.41194,0.41194,0.41194,0.41397,-0.49,14.0,54.0,...,2,0,0,0,N,N,N,N,N,N
36,000001.SZ,1991-05-31,0.40991,0.40991,0.40991,0.40991,0.41194,-0.49,1.0,4.0,...,2,2,0,0,N,N,N,N,N,N
37,000001.SZ,1991-06-03,0.40585,0.40585,0.40585,0.40585,0.40991,-0.99,7.0,26.0,...,2,2,0,0,N,N,N,N,N,N
38,000001.SZ,1991-06-04,0.40382,0.40382,0.40382,0.40382,0.40585,-0.50,1.0,4.0,...,2,2,0,0,N,N,N,N,N,N
39,000001.SZ,1991-06-06,0.39975,0.39975,0.39975,0.39975,0.40382,-1.01,4.0,15.0,...,2,2,0,0,N,N,N,N,N,N
40,000001.SZ,1991-06-07,0.39772,0.39772,0.39772,0.39772,0.39975,-0.51,1.0,4.0,...,2,2,0,0,N,N,N,N,N,N
41,000001.SZ,1991-06-10,0.39366,0.39366,0.39366,0.39366,0.39772,-1.02,15.0,55.0,...,2,2,0,0,N,N,N,N,N,N
42,000001.SZ,1991-06-11,0.39173,0.39173,0.39173,0.39173,0.39366,-0.49,12.0,44.0,...,2,2,0,0,N,N,N,N,N,N
43,000001.SZ,1991-06-12,0.38981,0.38981,0.38981,0.38981,0.39173,-0.49,15.0,55.0,...,2,2,0,0,N,N,N,N,N,N
44,000001.SZ,1991-06-13,0.38789,0.38789,0.38789,0.38789,0.38981,-0.49,34.0,123.0,...,2,2,0,0,N,N,N,N,N,N
45,000001.SZ,1991-06-14,0.38596,0.38596,0.38596,0.38596,0.38789,-0.50,7.0,25.0,...,2,2,0,0,N,N,N,N,N,N
46,000001.SZ,1991-06-17,0.38211,0.38211,0.38211,0.38211,0.38596,-1.00,5.0,18.0,...,2,2,0,0,N,N,N,N,N,N
47,000001.SZ,1991-06-18,0.38019,0.38019,0.38019,0.38019,0.38211,-0.50,10.0,35.0,...,2,2,0,0,N,N,N,N,N,N
48,000001.SZ,1991-06-19,0.37826,0.37826,0.37826,0.37826,0.38019,-0.51,57.0,202.0,...,2,2,0,0,N,N,N,N,N,N
49,000001.SZ,1991-06-20,0.37634,0.37634,0.37634,0.37634,0.37826,-0.51,30.0,105.0,...,2,2,0,0,N,N,N,N,N,N

In [6]:
tech_df = extract_rows_from_n(df=tech_df, group_by="ts_code")

In [7]:
tech_df = map_labels(tech_df)

In [8]:
tech_df

,ts_code,trade_date,open,high,low,close,pre_close,pct_change,vol,amount,...,kdj_status,rsi_status,macd_status,is_t_shape,top_or_bottom,top_or_bottom_stat,top_bottom_volatility_stat,top_or_bottom_stat_optimized,top_or_bottom_optimized,top_bottom_volatility_optimized
200,000001.SZ,1992-02-27,0.57166,0.57725,0.56794,0.57725,0.56887,1.4700,2033.00,6259.00,...,0,0,0,0,0,0,0,0,0,0
201,000001.SZ,1992-02-28,0.57725,0.59121,0.57725,0.58749,0.57725,1.7700,2335.00,7346.00,...,0,0,0,0,0,0,0,0,0,0
202,000001.SZ,1992-03-02,0.59028,0.59587,0.58842,0.59028,0.58749,0.4800,3137.00,9962.00,...,0,0,0,0,2,0,0,0,2,0
203,000001.SZ,1992-03-03,0.59214,0.59307,0.58749,0.59028,0.59028,0.0000,3150.00,9984.00,...,0,0,0,0,1,0,0,0,1,0
204,000001.SZ,1992-03-04,0.59214,0.59400,0.58749,0.59121,0.59028,0.1600,2288.00,7248.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886250,001222.SZ,2025-06-20,19.88000,20.43000,19.79000,19.83000,19.95000,-0.6015,45489.80,90992.54,...,0,0,1,0,0,0,0,0,0,0
2886251,001222.SZ,2025-06-23,19.79000,20.48000,19.54000,19.89000,19.83000,0.3026,49211.20,98012.46,...,0,0,1,0,2,0,0,0,0,0
2886252,001222.SZ,2025-06-24,20.10000,21.04000,19.95000,20.42000,19.89000,2.6647,75317.80,155035.77,...,0,0,1,0,0,0,0,0,0,0
2886253,001222.SZ,2025-06-25,20.65000,21.09000,19.92000,20.10000,20.42000,-1.5671,62527.89,126904.16,...,2,0,1,0,2,2,0,2,2,0
2886254,001222.SZ,2025-06-26,20.11000,20.11000,19.36000,19.57000,20.10000,-2.6368,57192.80,112100.97,...,2,0,1,0,1,0,0,0,1,0

In [11]:
check_nan_values(tech_df)

                        column_name  nan_count  total_count  nan_ratio
0                           ts_code          0      2792672        0.0
1                        trade_date          0      2792672        0.0
2                              open          0      2792672        0.0
3                              high          0      2792672        0.0
4                               low          0      2792672        0.0
..                              ...        ...          ...        ...
65               top_or_bottom_stat          0      2792672        0.0
66       top_bottom_volatility_stat          0      2792672        0.0
67     top_or_bottom_stat_optimized          0      2792672        0.0
68          top_or_bottom_optimized          0      2792672        0.0
69  top_bottom_volatility_optimized          0      2792672        0.0

[70 rows x 4 columns]

                        column_name  nan_count  total_count  nan_ratio
0                           ts_code          0      2792672        0.0
1                        trade_date          0      2792672        0.0
2                              open          0      2792672        0.0
3                              high          0      2792672        0.0
4                               low          0      2792672        0.0
..                              ...        ...          ...        ...
65               top_or_bottom_stat          0      2792672        0.0
66       top_bottom_volatility_stat          0      2792672        0.0
67     top_or_bottom_stat_optimized          0      2792672        0.0
68          top_or_bottom_optimized          0      2792672        0.0
69  top_bottom_volatility_optimized          0      2792672        0.0

[70 rows x 4 columns]

In [10]:
tech_df = drop_nan_values(tech_df)

In [12]:
tech_df.to_csv(f"{dataset_training}mapped_tech_pattern_{freq}.csv", index=False)